### PR TITLE
Add required type registration for Tentacle Manager

### PR DESCRIPTION
**Pull request by scme0**
# Background

Part of #project-k8s-agent

I made a boo boo and broke tentacle manager by not including some required type registrations. In https://github.com/OctopusDeploy/OctopusTentacle/pull/674

[Slack thread](https://octopusdeploy.slack.com/archives/C03SG0LFJHX/p1705997305750549)

# How to review this PR

Quality :heavy_check_mark:

# Pre-requisites

- [ ] I have read [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/main/docs/CONTRIBUTING.internal.md) for help deciding when and where it's appropriate to make an issue.
- [ ] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
- [ ] I have considered appropriate testing for my change.

### CODE REVIEW

**Review by LukeButters — APPROVED** [review]
Do make sure that tentacle manager is manually tested to be working.

Were any other tentacle binaries affected?

**Comment by scme0** [comment]
I'm a bit hamstrung in testing this because I'm on a mac. Weirdly enough, I can build the tentacle manager with Rider on the mac (for net framework 4.8) and run it in a Windows VM, but it fails to find the `Tentacle.exe` file, my guess is because it's just from the bin folder? It showed me at least that it's now not hitting the autofac exception. I'm just waiting for the `Build: Tentacle (Windows)` step to complete on team city before manually testing it again to make sure it works.

Tentacle itself should be fine because that's what we use for the agent (albeit the linux version). I'm going to install a tentacle with the net48 version and make sure it runs correctly before I merge this in 👍

**Comment by scme0** [comment]
@LukeButters I have installed and manually tested the tentacle manager and I have a listening Tentacle which is running the new version which is connecting correctly with my local octopus instance. So I think it's ok.

**Comment by LukeButters** [comment]
@scme0 Lets merge this in and in following PRs lets add tests and other changes to reduce the chance of this issue again.

**Pull request merged**
